### ISSUE TITLE
Maven Build is failing with this error 'java: package com.fasterxml.jackson.datatype.jdk8 does not exist'

### ISSUE THREAD

**Issue by Kannan0893** [prashant-ramcharan/courgette-jvm#400]
Hi @prashant-ramcharan ,

i am using courgette report for a while in my automation project .. instead of dependency i am directly using the courgette packages in my framework .its working fine with courgette package of 6.9.0 version .. now i have tried to update the packages with latest version then i ran into this issue

i have tried few other ways to solve this problem but nothing is working ,so better ask you on this issue 

after updating the latest packages ,my maven build is failing with compilation errors

please check and let me know if i need to change anything 

<img width="1687" alt="image" src="https://github.com/prashant-ramcharan/courgette-jvm/assets/86278549/a674801b-38a9-4dec-b190-a63126a1fba3">

Thanks,
Kannan P

**Comment by Kannan0893** [comment]
my bad ,i didnt check the dependency .. thanks @prashant-ramcharan .. we can close this ticket 
 one last question ,in courgette latest version we dont have this file `ApiExtentReport` under extend reports package .is there any particular reason for this file removed from latest version ?

Thanks,
kannan P

**Comment by prashant-ramcharan** [comment]
`ApiExtentReport` is not a class within Courgette (_and has never been_)

https://github.com/prashant-ramcharan/courgette-jvm/tree/master/src/main/java/courgette/integration/extentreports

This package has not changed for a while now.
